### ISSUE TITLE
Problem with NuPIC Examples - No Math Model Error

### ISSUE THREAD

**Issue by jburman789** [numenta/nupic-linux64#33]
I am new to NuPIC and I have downloaded and installed the software from GitHub.  However, when I attempt to run the examples, I continually get the ImportError: No module named math.  The math module is imported is several examples and when I enter python, I can import math.  How can I correct the error I am receiving when trying the NuPIC examples?  Thanks in advance,

python hierarchy_network_demo.py
Traceback (most recent call last):
  File "hierarchy_network_demo.py", line 38, in <module>
    from nupic.algorithms.anomaly import computeRawAnomalyScore
  File "/home/jerry/MATLAB/R2014b/bin/NuPic/nupic/algorithms/__init__.py", line 28, in <module>
    from nupic.bindings.math import NearestNeighbor
ImportError: No module named math

**Comment by rhyolight** [comment]
@jburman789 This means that NuPIC was not installed properly. How did you install it?

Also, this is not the right repository to create this issue. Please see http://numenta.org/bug-report.html

**Comment by jburman789** [comment]
I downloaded NuPIC from GitHub and followed the Linux installation instructions.  When I visited your suggested URL, it put me back where I entered my original bug report?

**Comment by rhyolight** [comment]
@jburman789 No, that is a different repository. Best to report your problem on the mailing list before creating an issue. You'll get more help there up front.

**Comment by jburman789** [comment]
Ok … where do I find the appropriate mailing list on GitHub?

Thanks

**Comment by rhyolight** [comment]
Never mind about the mailing list, seems like you are getting traction on https://github.com/numenta/nupic/issues/2086
